version: "3"

services:
  # Servicio para el motor de la base de datos MySQL
  mysql:
    image: mysql
    container_name: mi-mysql
    volumes:
      - mi-mysql-vol:/var/lib/mysql # Volumen para almacenar datos de la base de datos
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
    networks:
      - mi-mysqlred # Conectar el contenedor a la red personalizada

  # Servicio para la interfaz de usuario de phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: mi-dashboard
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8080:80" # Mapear el puerto 8080 del host al puerto 80 del contenedor de phpMyAdmin
    networks:
      - mi-mysqlred # Conectar el contenedor a la red personalizada

networks:
  mi-mysqlred:
    driver: bridge # Configurar una red puente personalizada

volumes:
  mi-mysql-vol: # Definir un volumen para almacenar datos persistentes de MySQL
