# Usa la imagen base de Node 14
FROM node:14

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /var/app

# Copia los archivos necesarios al directorio de trabajo
COPY . .

# Comando para arrancar el proyecto
CMD ["npm", "start"]
